-- DataArena: SQL Learning Roadmap — bulk insert topics
-- Run in Supabase → SQL Editor
--
-- sortOrder = YOUR roadmap number (same as 1, 2, 3, 4 in your list)
--   Topic 1 manual → sortOrder 1
--   Topic 2 manual → sortOrder 2
--   Topic 3 Types of Databases → sortOrder 3  (first row in this file)
--   ...
--   Topic 136 → sortOrder 136
--
-- In Supabase Table Editor, column is named: sortOrder

INSERT INTO topics (
  id, "categoryId", name, slug, description,
  "sortOrder", published, "openForAuthors", status, "claimedById",
  "createdAt", "updatedAt"
)
SELECT gen_random_uuid()::text, 'cmryjbyes000232la8qjvjb81',
  t.name, t.slug, t.description, t.sort_order,
  true, true, 'OPEN'::"TopicStatus", NULL, NOW(), NOW()
FROM ( VALUES
    (3, 'Types of Databases (Relational vs NoSQL)', 'types-of-databases-relational-vs-nosql', 'Explore database types and understand when to use each.'),
    (4, 'What is DBMS?', 'what-is-dbms', 'Understand the role and responsibilities of a Database Management System.'),
    (5, 'What is RDBMS?', 'what-is-rdbms', 'Learn how relational databases organize data using tables and relationships.'),
    (6, 'What is SQL?', 'what-is-sql', 'Discover what SQL is and how it communicates with relational databases.'),
    (7, 'SQL Command Categories (DDL, DML, DQL, DCL, TCL)', 'sql-command-categories-ddl-dml-dql-dcl-tcl', 'Learn the five categories of SQL commands and their purpose.'),
    (8, 'SQL Data Types', 'sql-data-types', 'Understand how data types define the values stored in columns.'),
    (9, 'Creating Your First Database', 'creating-your-first-database', 'Create your first database and understand the process.'),
    (10, 'Creating Tables', 'creating-tables', 'Learn how to design and create well-structured tables.'),
    (11, 'SQL Constraints', 'sql-constraints', 'Understand how constraints maintain data integrity.'),
    (12, 'SQL Naming Conventions & Best Practices', 'sql-naming-conventions-best-practices', 'Write clean, readable, and maintainable SQL.'),
    (13, 'INSERT Statement', 'insert-statement', 'Learn how to add new records into a table.'),
    (14, 'INSERT Multiple Rows', 'insert-multiple-rows', 'Insert multiple records efficiently in a single query.'),
    (15, 'UPDATE Statement', 'update-statement', 'Modify existing records safely and efficiently.'),
    (16, 'DELETE Statement', 'delete-statement', 'Remove specific records using conditions.'),
    (17, 'TRUNCATE vs DELETE vs DROP', 'truncate-vs-delete-vs-drop', 'Understand the differences between these commands.'),
    (18, 'ALTER TABLE', 'alter-table', 'Modify the structure of existing tables.'),
    (19, 'RENAME TABLE', 'rename-table', 'Rename tables without losing data.'),
    (20, 'COPY Data Between Tables', 'copy-data-between-tables', 'Move or duplicate data between tables.'),
    (21, 'UPSERT (MERGE)', 'upsert-merge', 'Insert or update records in one operation.'),
    (22, 'AUTO_INCREMENT / IDENTITY', 'auto-increment-identity', 'Generate unique IDs automatically.'),
    (23, 'Default Values', 'default-values', 'Assign automatic default values to columns.'),
    (24, 'NULL Values', 'null-values', 'Understand NULL and how to handle missing data.'),
    (25, 'SELECT Statement', 'select-statement', 'Retrieve data from one or more tables.'),
    (26, 'DISTINCT', 'distinct', 'Remove duplicate values from query results.'),
    (27, 'WHERE Clause', 'where-clause', 'Filter records based on conditions.'),
    (28, 'ORDER BY', 'order-by', 'Sort query results in ascending or descending order.'),
    (29, 'LIMIT / OFFSET', 'limit-offset', 'Control the number of returned rows.'),
    (30, 'TOP Clause', 'top-clause', 'Retrieve the first N rows.'),
    (31, 'FETCH FIRST', 'fetch-first', 'Limit results using SQL standard syntax.'),
    (32, 'Aliases', 'aliases', 'Improve query readability using aliases.'),
    (33, 'Arithmetic Operations', 'arithmetic-operations', 'Perform calculations within SQL queries.'),
    (34, 'Comparison Operators', 'comparison-operators', 'Compare values using relational operators.'),
    (35, 'Logical Operators', 'logical-operators', 'Combine multiple conditions effectively.'),
    (36, 'IN Operator', 'in-operator', 'Filter values from a predefined list.'),
    (37, 'BETWEEN', 'between', 'Filter values within a specified range.'),
    (38, 'LIKE', 'like', 'Search using wildcard pattern matching.'),
    (39, 'IS NULL', 'is-null', 'Identify missing or unknown values.'),
    (40, 'COUNT()', 'count', 'Count rows matching a condition.'),
    (41, 'SUM()', 'sum', 'Calculate the total of numeric values.'),
    (42, 'AVG()', 'avg', 'Find the average of numeric values.'),
    (43, 'MIN()', 'min', 'Retrieve the smallest value.'),
    (44, 'MAX()', 'max', 'Retrieve the largest value.'),
    (45, 'GROUP BY', 'group-by', 'Group rows before aggregation.'),
    (46, 'HAVING', 'having', 'Filter grouped results after aggregation.'),
    (47, 'GROUPING SETS', 'grouping-sets', 'Generate multiple grouping combinations.'),
    (48, 'ROLLUP', 'rollup', 'Create hierarchical subtotals.'),
    (49, 'CUBE', 'cube', 'Generate all possible aggregation combinations.'),
    (50, 'Why Joins Exist', 'why-joins-exist', 'Understand why joins are essential.'),
    (51, 'INNER JOIN', 'inner-join', 'Retrieve matching rows from both tables.'),
    (52, 'LEFT JOIN', 'left-join', 'Return all left table rows with matching right rows.'),
    (53, 'RIGHT JOIN', 'right-join', 'Return all right table rows with matching left rows.'),
    (54, 'FULL OUTER JOIN', 'full-outer-join', 'Return all matching and non-matching rows.'),
    (55, 'CROSS JOIN', 'cross-join', 'Generate the Cartesian product.'),
    (56, 'SELF JOIN', 'self-join', 'Join a table with itself.'),
    (57, 'NATURAL JOIN', 'natural-join', 'Automatically join using common columns.'),
    (58, 'SEMI JOIN', 'semi-join', 'Return rows with matching records.'),
    (59, 'ANTI JOIN', 'anti-join', 'Return rows without matching records.'),
    (60, 'Multi-table Joins', 'multi-table-joins', 'Combine data from multiple tables.'),
    (61, 'Join Optimization', 'join-optimization', 'Improve join performance.'),
    (62, 'CASE WHEN', 'case-when', 'Add conditional logic to SQL queries.'),
    (63, 'COALESCE', 'coalesce', 'Return the first non-NULL value.'),
    (64, 'NULLIF', 'nullif', 'Return NULL when values match.'),
    (65, 'EXISTS', 'exists', 'Check whether matching rows exist.'),
    (66, 'ANY', 'any', 'Compare against any value in a subquery.'),
    (67, 'ALL', 'all', 'Compare against all values in a subquery.'),
    (68, 'Subqueries', 'subqueries', 'Nest queries inside other queries.'),
    (69, 'Correlated Subqueries', 'correlated-subqueries', 'Execute subqueries dependent on outer queries.'),
    (70, 'Common Table Expressions (CTEs)', 'common-table-expressions-ctes', 'Write readable and reusable queries.'),
    (71, 'Recursive CTEs', 'recursive-ctes', 'Solve hierarchical problems.'),
    (72, 'UNION', 'union', 'Combine unique rows.'),
    (73, 'UNION ALL', 'union-all', 'Combine all rows.'),
    (74, 'INTERSECT', 'intersect', 'Return common rows.'),
    (75, 'EXCEPT', 'except', 'Return rows from one query not in another.'),
    (76, 'MERGE', 'merge', 'Synchronize data between tables.'),
    (77, 'Introduction to Window Functions', 'introduction-to-window-functions', 'Understand analytical functions without grouping rows.'),
    (78, 'OVER Clause', 'over-clause', 'Define the window for calculations.'),
    (79, 'PARTITION BY', 'partition-by', 'Divide data into logical partitions.'),
    (80, 'ORDER BY in Window Functions', 'order-by-in-window-functions', 'Control calculation order.'),
    (81, 'ROW_NUMBER()', 'row-number', 'Assign unique sequential row numbers.'),
    (82, 'RANK()', 'rank', 'Rank rows while allowing gaps.'),
    (83, 'DENSE_RANK()', 'dense-rank', 'Rank rows without gaps.'),
    (84, 'NTILE()', 'ntile', 'Divide rows into buckets.'),
    (85, 'LEAD()', 'lead', 'Access following row values.'),
    (86, 'LAG()', 'lag', 'Access previous row values.'),
    (87, 'FIRST_VALUE()', 'first-value', 'Retrieve the first value.'),
    (88, 'LAST_VALUE()', 'last-value', 'Retrieve the last value.'),
    (89, 'Primary Key', 'primary-key', 'Uniquely identify each record.'),
    (90, 'Foreign Key', 'foreign-key', 'Maintain relationships between tables.'),
    (91, 'Candidate Key', 'candidate-key', 'Identify all possible unique keys.'),
    (92, 'Composite Key', 'composite-key', 'Create uniqueness using multiple columns.'),
    (93, 'Surrogate Key', 'surrogate-key', 'Use artificial identifiers.'),
    (94, 'Normalization', 'normalization', 'Reduce redundancy.'),
    (95, 'Denormalization', 'denormalization', 'Improve performance by reducing joins.'),
    (96, 'ER Diagrams', 'er-diagrams', 'Design relationships visually.'),
    (97, 'Relationships', 'relationships', 'Understand table relationships.'),
    (98, 'Schema Design Best Practices', 'schema-design-best-practices', 'Design scalable schemas.'),
    (99, 'SQL Execution Order', 'sql-execution-order', 'Understand how SQL executes internally.'),
    (100, 'Query Execution Plan', 'query-execution-plan', 'Analyze query execution.'),
    (101, 'Indexes', 'indexes', 'Speed up data retrieval.'),
    (102, 'Clustered Index', 'clustered-index', 'Understand physical data organization.'),
    (103, 'Non-clustered Index', 'non-clustered-index', 'Use separate index structures.'),
    (104, 'Composite Index', 'composite-index', 'Optimize multi-column queries.'),
    (105, 'Covering Index', 'covering-index', 'Avoid table lookups.'),
    (106, 'Statistics', 'statistics', 'Help optimizers estimate costs.'),
    (107, 'Partitioning', 'partitioning', 'Split large tables.'),
    (108, 'Query Optimization Techniques', 'query-optimization-techniques', 'Write faster SQL.'),
    (109, 'Transactions', 'transactions', 'Execute operations safely.'),
    (110, 'ACID Properties', 'acid-properties', 'Understand reliable transactions.'),
    (111, 'Isolation Levels', 'isolation-levels', 'Control concurrent behavior.'),
    (112, 'Locks', 'locks', 'Protect data consistency.'),
    (113, 'Deadlocks', 'deadlocks', 'Identify and resolve deadlocks.'),
    (114, 'OLTP vs OLAP', 'oltp-vs-olap', 'Compare transactional and analytical systems.'),
    (115, 'Data Warehouse', 'data-warehouse', 'Understand centralized analytical storage.'),
    (116, 'Data Mart', 'data-mart', 'Learn purpose-specific databases.'),
    (117, 'Fact Tables', 'fact-tables', 'Store measurable business events.'),
    (118, 'Dimension Tables', 'dimension-tables', 'Store descriptive business attributes.'),
    (119, 'Star Schema', 'star-schema', 'Design efficient analytical schemas.'),
    (120, 'Snowflake Schema', 'snowflake-schema', 'Normalize dimensions.'),
    (121, 'Slowly Changing Dimensions (SCD)', 'slowly-changing-dimensions-scd', 'Manage historical changes.'),
    (122, 'Incremental Loading', 'incremental-loading', 'Load only changed records.'),
    (123, 'Change Data Capture (CDC)', 'change-data-capture-cdc', 'Capture data changes.'),
    (124, 'SQL in Apache Spark', 'sql-in-apache-spark', 'Use distributed SQL in Spark.'),
    (125, 'SQL in Apache Hive', 'sql-in-apache-hive', 'Query big data with Hive.'),
    (126, 'SQL in Snowflake', 'sql-in-snowflake', 'Use SQL in Snowflake.'),
    (127, 'SQL in BigQuery', 'sql-in-bigquery', 'Analyze large datasets.'),
    (128, 'SQL in Databricks', 'sql-in-databricks', 'Leverage SQL in Databricks.'),
    (129, '100 SQL Interview Questions', '100-sql-interview-questions', 'Practice the most frequently asked SQL interview questions.'),
    (130, '50 Easy SQL Problems', '50-easy-sql-problems', 'Build confidence with beginner-friendly exercises.'),
    (131, '50 Medium SQL Problems', '50-medium-sql-problems', 'Strengthen problem-solving skills.'),
    (132, '50 Hard SQL Problems', '50-hard-sql-problems', 'Master advanced SQL challenges.'),
    (133, 'Company-wise SQL Questions', 'company-wise-sql-questions', 'Prepare for top company interviews.'),
    (134, 'Real-world Business Case Studies', 'real-world-business-case-studies', 'Solve practical business scenarios.'),
    (135, 'SQL Debugging Exercises', 'sql-debugging-exercises', 'Learn to identify and fix SQL errors.'),
    (136, 'Query Optimization Exercises', 'query-optimization-exercises', 'Improve query performance through practice.')
) AS t(sort_order, name, slug, description)
ON CONFLICT ("categoryId", slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description,
  "sortOrder"=EXCLUDED."sortOrder", published=EXCLUDED.published,
  "openForAuthors"=EXCLUDED."openForAuthors", status=EXCLUDED.status,
  "updatedAt"=NOW();

-- Fix your 2 manual topics to match roadmap numbers:
UPDATE topics SET "sortOrder" = 1, "updatedAt" = NOW()
WHERE "categoryId" = 'cmryjbyes000232la8qjvjb81' AND name = 'What is Data?';
UPDATE topics SET "sortOrder" = 2, "updatedAt" = NOW()
WHERE "categoryId" = 'cmryjbyes000232la8qjvjb81' AND name = 'What is a Database?';

SELECT "sortOrder", name FROM topics
WHERE "categoryId" = 'cmryjbyes000232la8qjvjb81'
ORDER BY "sortOrder" LIMIT 10;
